# Generated by Django 4.1.7 on 2023-04-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsApp', '0002_genres_stories_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genres',
            name='name',
            field=models.CharField(choices=[('Fantasy', 'Fantasy'), ('Folklore', 'Folklore'), ('HistoricalFiction', 'HistoricalFiction'), ('Horror', 'Horror'), ('Mystery', 'Mystery'), ('Poetry', 'Poetry'), ('Romance', 'Romance'), ('ScienceFiction', 'ScienceFiction'), ('SelfHelp', 'SelfHelp')], max_length=50),
        ),
    ]
