# Generated by Django 4.1.7 on 2023-04-11 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountsApp', '0004_rename_name_stories_sname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stories',
            old_name='sname',
            new_name='genres',
        ),
    ]
