# Generated by Django 4.1.7 on 2023-04-11 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountsApp', '0005_rename_sname_stories_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='genres',
            field=models.ForeignKey(choices=[('Fantasy', 'Fantasy'), ('Folklore', 'Folklore'), ('HistoricalFiction', 'HistoricalFiction'), ('Horror', 'Horror'), ('Mystery', 'Mystery'), ('Poetry', 'Poetry'), ('Romance', 'Romance'), ('ScienceFiction', 'ScienceFiction'), ('SelfHelp', 'SelfHelp')], on_delete=django.db.models.deletion.CASCADE, to='accountsApp.genres'),
        ),
    ]
