# Generated by Django 4.1.7 on 2023-04-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsApp', '0006_alter_stories_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='story',
            field=models.TextField(max_length=5000),
        ),
    ]
